export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const ERROR_IN_USER_DATA = "ERROR_IN_USER_DATA";
export const GET_REPORT_DATA = "GET_REPORT_DATA";
export const GET_REPORT_DATA_ERROR = "GET_REPORT_DATA_ERROR";